name: Evaluate Student Submission

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install --upgrade pip
          pip3 install black codespell flake8 black[jupyter]

      - name: Spell check with codespell
        run: |
          codespell --ignore-words .github/workflows/my_dictionary.txt sample_code_submission

      - name: Format check with black
        run: |
          black --check . 

  eval:
    runs-on: ubuntu-latest
    needs: checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install --upgrade pip
          pip3 install numpy pandas pyarrow matplotlib xgboost scikit-learn nflows lightgbm seaborn iminuit higgsml
          pip3 install keras
          pip3 install tensorflow

      - name: Run evaluation
        run: |
          python3 -m HiggsML.run_competition \
            --submission sample_code_submission \
            --output sample_result_submission \
            --num-of-sets 2 \
            --num-pseudo-experiments 5 
